services:
  postgres:
    image: postgres:17
    container_name: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5231:5432"

    volumes:
      - bent_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  bent_data:
